### PR TITLE
Developers no longer have to manually serialize their responses in ha…

### PR DESCRIPTION
**Pull request by autodidaddict**
…ndlers

### CODE REVIEW

**Comment by ewbankkit** [comment]
Is it possible to have something similar on the dispatcher side so a capability provider doesn't have to `serialize`/`deserialize` explicitly?

**Comment by autodidaddict** [comment]
Yes im going to look into that right after this

**Review by bketelsen — APPROVED** [review]

**Comment by autodidaddict** [comment]
@ewbankkit I did some poking around and it looks trickier than I thought. The issue is that `Dispatcher` is a trait, and if I try and add generic type parameters to the function signature on it, that trait then becomes "unboxable" (you get the `trait cannot be made into an object` error), because Rust can't inline that call into a type-bound call.

**Comment by autodidaddict** [comment]
We could "bubble up" the type binding if a dispatcher were to always be bound to a single data type at compile time, but since capability providers can dispatch many different messages to actors (the reverse is also true), it doesn't look like I can get around passing a strong type back and forth, like the `Vec<u8>`

**Comment by ewbankkit** [comment]
Yes, I see the problem with that.

**Pull request merged**
